language: node_js

node_js:
- "4.5.0"

notifications:
  email:
    -srameshv@indiana.edu

branches:
  only:
    - feature/feature-13-forecast-trigger

sudo: true

before_install:
- cd core/javascript/ForecastTrigger/

install:
- npm install

before_deploy:
  - cd ..
  - zip -r ForecastTrigger.zip ForecastTrigger || true
  - mkdir -p "teambash"
  - mv ForecastTrigger.zip teambash/ForecastTrigger.zip || true

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # declared in Travis repo settings
    secret_access_key: $AWS_SECRET_KEY
    bucket: team-bash
    local_dir: teambash
    region: us-east-1
    skip_cleanup: true
    acl: public_read
    detect_encoding: true
    on:
      branch: feature/feature-13-forecast-trigger
